config/routes.rb
Documentation::Engine.routes.draw do
  scope '/v/:version_ordinal', :constraints => { :version_ordinal => /[^\/]+/ } do
    match 'new(/*path)', :to => 'pages#new', :as => 'new_page', :via => [:get, :post]
    match 'positioning(/*path)', :to => 'pages#positioning', :as => 'page_positioning', :via => [:get, :post]
    match 'edit(/*path)', :to => 'pages#edit', :as => 'edit_page', :via => [:get, :patch]
    match 'delete(/*path)', :to => 'pages#destroy', :as => 'delete_page', :via => [:delete]
    match 'screenshot', :to => 'pages#screenshot', :as => 'upload_screenshot', :via => [:get, :post]
    get 'search', :to => 'pages#search', :as => 'search'
    get '*path' => 'pages#show', :as => 'page'
    root :to => 'pages#index'
  end
  match '/version_locales/new/:id', :to => 'version_locales#new', :as => 'new_version_locale', :via => [:get, :patch]
  match '/versions/new', :to => 'versions#new', :as => 'new_version', :via => [:get, :post]
  match '/versions/edit/:id', :to => 'versions#edit', :as => 'edit_version', :via => [:get, :patch]
  match '/versions/delete/:id', :to => 'versions#destroy', :as => 'delete_version', :via => [:delete]
  match '/versions', :to => 'versions#index', :as => 'versions', :via => [:get]
  match '/screenshots/delete/:id', :to => 'screenshots#destroy', :as => 'delete_screenshot', :via => [:delete]
  match '/screenshots', :to => 'screenshots#index', :as => 'screenshots', :via => [:get]
  get 'set_language/:locale', to: 'languages#set_language', as: 'set_language'
  root :to => 'pages#index', :as => 'unspecified_root'
end

app/models/documentation/page.rb
module Documentation
  class Page < ActiveRecord::Base

    delegate :ordinal, to: :version, prefix: true

    validates :title, :presence => true
    validates :position, :presence => true
    validates :permalink, :presence => true, :uniqueness => {:scope => [:parent_id, :version_id, :locale]}

    default_scope -> { order(:position) }
    scope :roots, -> { where(:parent_id => nil) }
    scope :in_version, -> (version_id) { where(:version_id => version_id) }
    scope :localized, -> (locale) { where(:locale => locale) }

    parent_options = {:class_name => "Documentation::Page", :foreign_key => 'parent_id'}
    parent_options[:optional] = true if ActiveRecord::VERSION::MAJOR >= 5
    belongs_to :parent, parent_options

    version_options = {:class_name => "Documentation::Version"}
    belongs_to :version, version_options

    before_validation do
      if self.position.blank?
        last_position = self.class.unscoped.where(:parent_id => self.parent_id).order(:position => :desc).first
        self.position = last_position ? last_position.position + 1 : 1
      end
    end

    before_validation :set_version
    before_validation :set_permalink
    before_save :compile_content

    #
    # Ensure the page is updated in the index after saving/destruction
    #
    after_commit :index, :on => [:create, :update]
    after_commit :delete_from_index, :on => :destroy

    #
    # Store all the parents of this object. THis is automatically populated when it is loaded
    # from a path
    #
    attr_accessor :parents

    #
    # Set the permalink for this page
    #
    def set_permalink
      return if self.title.blank?
      proposed_permalink = self.title.parameterize
      index = 1
      while self.permalink.blank?
        if self.class.where(:permalink => proposed_permalink, :parent_id => self.parent_id, :version_id => self.version_id).exists?
          index += 1
          proposed_permalink = self.title.parameterize + "-#{index}"
        else
          self.permalink = proposed_permalink
        end
      end
    end

    #
    # Set the version for this page
    #
    def set_version
      return if self.version_id.present?
      parent_record = self.class.unscoped.where(:id => self.parent_id).first if self.parent_id.present?
      self.version_id = parent_record&.version_id
    end

    #
    # Return a default empty array for parents
    #
    def parents
      @parents ||= self.parent ? [self.parent.parents, self.parent].flatten : []
    end

    #
    # Return a full breadcrumb to this page (as it has been loaded)
    #
    def breadcrumb
      @breadcrumb ||= [parents, new_record? ? nil : self].flatten.compact
    end

    #
    # Return the path where this page can be viewed in the site
    #
    def preview_path
      if path = Documentation.config.preview_path_prefix
        "#{path}#{full_permalink}"
      else
        nil
      end
    end

    #
    # Return a full permalink tot his page
    #
    def full_permalink
      @full_permalink ||= begin
        if parents.empty?
          self.permalink
        else
          previous = breadcrumb.compact.map(&:permalink).compact
          previous.empty? ? self.permalink : previous.join('/')
        end
      end
    end

    #
    # Return all child pages
    #
    def children
      @children ||= begin
        if self.new_record?
          self.class.none
        else
          children = self.class.where(:parent_id => self.id)
          children.each { |c| c.parents = [parents, self].flatten }
          children
        end
      end
    end

    #
    # Does this page have children?
    #
    def has_children?
      !children.empty?
    end

    #
    # Return pages which should be included in the navigation
    #
    def navigation
      if has_children?
        root_parent = parents[-1]
        if root_parent.nil?
          pages = self.class.roots.localized(I18n.locale)
        else
          pages = (root_parent || self).children
        end
      else
        root_parent = parents[-2] || parents[-1]
        if root_parent.nil? || (root_parent.parent.nil? && parents.size <= 1)
          pages = self.class.roots.localized(I18n.locale)
        else
          pages = (root_parent || self).children
        end
      end


      pages.map do |c|
        child_pages = []
        child_pages = c.children if breadcrumb.include?(c)
        [c, child_pages]
      end
    end

    #
    # Create the compiled content
    #
    def compile_content
      mr = Documentation::MarkdownRenderer.new(:with_toc_data => true)
      mr.page = self
      rc = Redcarpet::Markdown.new(mr, :space_after_headers => true, :fenced_code_blocks => true, :no_intra_emphasis => true, :highlight => true)
      self.compiled_content = rc.render(self.content.to_s).html_safe
    end

    #
    # Index this page
    #
    def index
      if searcher = Documentation.config.searcher
        searcher.index(self)
      end
    end

    #
    # Delete this page from the index
    #
    def delete_from_index
      if searcher = Documentation.config.searcher
        searcher.delete(self)
      end
    end

    #
    # Does this page have a parent?
    #
    def root?
      parent_id.nil?
    end

    #
    # Find a page using the searcher if one exists otherwise just fall back to AR
    # searching. Returns a Documentation::SearchResult object.
    #
    def self.search(query, options = {})
      if searcher = Documentation.config.searcher
        searcher.search(query, options)
      end
    end

    #
    # Find a page by passing a path to the page from the root of the
    # site
    #
    def self.find_from_path(version_id, path_string, options = {})
      raise ActiveRecord::RecordNotFound, "Couldn't find page without a path" if path_string.blank?
      locale = options[:locale] || I18n.locale
      path_parts = path_string.split('/')
      path = []
      path_parts.each_with_index do |p, i|
        page = self.where(:parent_id => (path.last ? path.last.id : nil), :version_id => version_id, :locale => locale).find_by_permalink(p)
        if page
          page.parents = path.dup
          page.parent = path.last
          path << page
        else
          raise ActiveRecord::RecordNotFound, "Couldn't find page at #{path_string}"
        end
      end
      path.last
    end

    #
    # Reorder pages
    #
    def self.reorder(parent, order = [])
      order = order.map(&:to_i)
      order = self.where(:parent_id => parent.id).map(&:id) if order.empty?
      order.each_with_index do |id, index|
        command = self.find_by_id!(id)
        command.position = index + 1
        command.save
      end
    end

    #
    # Duplicates page for other versions
    #
    def self.duplicate(base_page, options = {})
      duplicate_page = base_page.dup
      duplicate_page.assign_attributes(options)
      duplicate_page.save

      if base_page.has_children?
        base_page.children.each do |child_page|
          duplicate(child_page, options.tap { |opts| opts[:parent] = duplicate_page})
        end
      end
    end

  end
end

app/models/documentation/screenshot.rb
module Documentation
  class Screenshot < ActiveRecord::Base

    attachment :upload

    before_validation do
      if self.upload_file && self.alt_text.blank?
        self.alt_text = self.upload_file.original_filename
      end
      true
    end

    has_one :upload, lambda {
      select(:id, :token, :digest, :parent_id, :parent_type, :file_name, :file_type).where(:role => :upload)
    }, :class_name => 'Nifty::Attachments::Attachment', :as => :parent

    def untapped?
      @embedded ||= !Page.where('content LIKE ?', "%#{upload.path}%").any?
    end

  end
end

app/controllers/documentation/application_controller.rb
module Documentation
  class ApplicationController < ActionController::Base

    rescue_from Documentation::AccessDeniedError do |e|
      flash[:alert] = t('documentation.alerts.access_denied')
      do_redirect_back
    end

    rescue_from ActiveRecord::RecordNotFound do |e|
      flash[:alert] = t('documentation.alerts.no_record')
      redirect_to root_path(version_ordinal: @version&.ordinal)
    end

    before_action :set_locale
    before_action :set_version
    before_action do
      unless authorizer.can_use_ui?
        render :template => 'documentation/shared/not_found', :layout => false
      end
    end

    private

    def set_version
      return if params[:version_ordinal] == 'versions'
      @version = Documentation::Version.find_by(ordinal: params[:version_ordinal])
      if @version.blank?
        @latest_version = Documentation::Version.last
        if authorizer.can_use_ui?
          render :template => 'documentation/shared/choose_version'
        end
      end
    end

    def set_locale
      @application_locales = I18n.available_locales & Documentation.config.available_locales
      I18n.locale = session[:locale] || I18n.default_locale
    end

    def authorizer
      @authorizer ||= Documentation.config.authorizer.new(self)
    end

    def do_redirect_back(fallback_location: root_path(version_ordinal: @version&.ordinal))
      redirect_back(fallback_location: unspecified_root_path)
    rescue ActionController::RedirectBackError
      redirect_back(fallback_location: fallback_location)
    end

    helper_method :authorizer

  end
end

app/controllers/documentation/languages_controller.rb
module Documentation
  class LanguagesController < ApplicationController

    skip_before_action :set_version

    def set_language
      if params[:locale].present? && params[:locale].to_sym.in?(@application_locales)
        session[:locale] = params[:locale]
      else
        flash[:alert] = t('documentation.alerts.no_lang')
      end
      redirect_back(fallback_location: unspecified_root_path)
    end

  end
end

app/controllers/documentation/pages_controller.rb
module Documentation
  class PagesController < Documentation::ApplicationController

    before_action :find_page, :only => [:show, :edit, :new, :destroy, :positioning]

    def show
      authorizer.check! :view_page, @page
    end

    def edit
      authorizer.check! :edit_page, @page

      if request.patch?
        if @page.update_attributes(safe_params)
          redirect_to page_path(@page.full_permalink, version_ordinal: @version.ordinal), :notice => t('.notice')
          return
        end
      end
      render :action => "form"
    end

    def new
      authorizer.check! :add_page, @page

      parent = @page
      @page = Page.new(:version_id => @version.id, :locale => I18n.locale)
      if @page.parent = parent
        @page.parents = parent.breadcrumb
      end

      if request.post?
        @page.attributes = safe_params
        if @page.save
          redirect_to page_path(@page.full_permalink, version_ordinal: @version.ordinal), :notice => t('.notice')
          return
        end
      end
      render :action => "form"
    end

    def destroy
      authorizer.check! :delete_page, @page
      @page.destroy
      if params[:redirect_to].present?
        redirect_to params[:redirect_to].to_sym, :notice => t('.notice')
      else
        redirect_to @page.parent ? page_path(@page.parent.full_permalink, version_ordinal: @version.ordinal) : root_path, :notice => t('.notice')
      end
    end

    def screenshot
      authorizer.check! :upload, @page
      if request.post?
        @screenshot = Screenshot.new(screenshot_params)
        if @screenshot.save
          render :json => { :id => @screenshot.id, :title => @screenshot.alt_text, :path => @screenshot.upload.path }, :status => :created
        else
          render :json => { :errors => @screenshot.errors }, :status => :unprocessible_entity
        end
      else
        @screenshot = Screenshot.new
        render 'screenshot', :layout => false
      end
    end

    def positioning
      authorizer.check! :reposition_page, @page
      @pages = @page ? @page.children : Page.roots.in_version(@version.id).localized(I18n.locale)
      if request.post?
        Page.reorder(@page, params[:order])
        render :json => {:status => 'ok'}
      end
    end

    def search
      authorizer.check! :search
      @result = Documentation::Page.in_version(@version.id).search(params[:query], :page => params[:page].blank? ? 1 : params[:page].to_i) #, per_page: 20)
    end

    private

    def find_page
      if params[:path]
        @page = Page.find_from_path(@version.id, params[:path], locale: I18n.locale)
      end
    end

    def safe_params
      params.require(:page).permit(:title, :permalink, :content, :favourite)
    end

    def screenshot_params
      params.require(:screenshot).permit(:upload_file, :alt_text)
    end

  end
end

app/controllers/documentation/screenshots_controller.rb
module Documentation
  class ScreenshotsController < Documentation::ApplicationController

    skip_before_action :set_version
    before_action :find_screenshot, :only => [:destroy]

    def index
      @screenshots = Screenshot.all #Nifty::Attachments::Attachment.all
    end

    def destroy
      authorizer.check! :delete_screenshot, @screenshot
      @screenshot.destroy
      redirect_to screenshots_path, :notice => t('.notice')
    end

    private

    def find_screenshot
      if params[:id]
        @screenshot = Screenshot.find(params[:id])
      end
    end

  end
end

app/controllers/documentation/version_locales_controller.rb
module Documentation
  class VersionLocalesController < Documentation::ApplicationController

    skip_before_action :set_version
    before_action :find_version, :only => [:new]

    def new
      authorizer.check! :add_version


      if request.patch?
        @version.validate_new_locale(safe_params, @application_locales)

        if @version.errors.empty?
          @version.new_locale(safe_params[:base_locale], safe_params[:locale_added])

          redirect_to versions_path, :notice => t('.notice')
        else
          render :action => "form"
        end
        return
      end
      render :action => "form"
    end

    private

    def find_version
      if params[:id]
        @version = Version.find(params[:id])
      end
    end

    def safe_params
      params.require(:version).permit(:base_locale, :locale_added)
    end

  end
end

app/controllers/documentation/versions_controller.rb
module Documentation
  class VersionsController < Documentation::ApplicationController

    skip_before_action :set_version
    before_action :find_version, :only => [:edit, :destroy]

    def index
      @versions = Version.ordered
    end

    def new
      @version = Version.new
      authorizer.check! :add_version

      if request.post?
        @version.attributes = safe_params
        if @version.save
          redirect_to versions_path, :notice => t('.notice')
          return
        end
      end
      render :action => "form"
    end

    def edit
      authorizer.check! :edit_version, @version

      if request.patch?
        if @version.update_attributes(safe_params)
          redirect_to versions_path, :notice => t('.notice')
          return
        end
      end
      render :action => "form"
    end

    def destroy
      authorizer.check! :delete_version, @version
      @version.destroy
      redirect_to versions_path, :notice => t('.notice')
    end

    private

    def find_version
      if params[:id]
        @version = Version.find(params[:id])
      end
    end

    def safe_params
      params.require(:version).permit(:ordinal, :based_on)
    end

  end
end

app/helpers/documentation/application_helper.rb
module Documentation
  module ApplicationHelper

    include Documentation::ViewHelpers

    def flash_messages
      flashes = flash.collect do |key,msg|
        content_tag :div, content_tag(:p, h(msg)), :id => "flash-#{key}"
      end.join.html_safe
    end

  end
end

app/views/documentation/pages/_admin_buttons.html.haml
- canAdd = authorizer.can_add_page?(@page)
- canEdit = authorizer.can_edit_page?(@page)
- canReposition = authorizer.can_reposition_page?(@page)
- canDelete = authorizer.can_delete_page?(@page)

- if canAdd || canEdit || canReposition || canDelete
  %p.adminButtons
    - if canAdd
      = link_to t('.new'), new_page_path(@page.full_permalink, version_ordinal: @version.ordinal), :class => 'button new'

    - if canReposition && @page.has_children?
      = link_to t('.reorder'), page_positioning_path(@page.try(:full_permalink), version_ordinal: @version.ordinal), :class => 'button edit'

    - if canEdit
      = link_to t('.edit'), edit_page_path(@page.full_permalink, version_ordinal: @version.ordinal), :class => 'button edit'

    - if canDelete
      = link_to t('.delete'), delete_page_path(@page.full_permalink, version_ordinal: @version.ordinal), :class => 'button delete', :method => :delete, :data => {:confirm => t('.confirm_delete')}

app/views/documentation/pages/_markdown_hints.html.haml
- if Documentation.config.markdown_hints
  .markdownHints
    %h1= t('.title')
    %p= t('.column_1').html_safe
    %p= t('.column_2').html_safe

app/views/documentation/pages/form.html.haml
- @page_title = @page.breadcrumb.reverse.map(&:title).join(" - ")

%section.content.edit-article
  = documentation_breadcrumb_for @version, @page
  = form_for @page, :url => @page.new_record? ? new_page_path(@page.parent ? @page.parent.full_permalink : nil, version_ordinal: @version.ordinal) : edit_page_path(@page.full_permalink, version_ordinal: @version.ordinal), :html => {:class => 'pageForm'} do |f|
    = error_messages_for @page
    .title= f.text_field :title, :placeholder => t('.title_placeholder')
    .content~ f.text_area :content, :placeholder => t('.content_placeholder')
    = render 'markdown_hints'
    .clearfix
    %dl
      %dt= f.label :permalink
      %dd= f.text_field :permalink, :placeholder => t('.permalink_placeholder')

    %p.submit
      - if authorizer.can_upload?(@page)
        = link_to t('.add_screenshot'), upload_screenshot_path, :class => 'button preview js-screenshot'
      = f.submit t('.save'), :class => 'button'

app/views/documentation/pages/index.html.haml
%section.welcome
  %h1= t('.welcome_title', app_name: Documentation.config.app_name, version_ordinal: @version.ordinal)
  %h2= t('.welcome_text')

  - if Documentation.config.developer_tips
    .override
      %p= t('.developer_tip').html_safe

  - if @version.pages.localized(I18n.locale).empty?
    .override
      %p= t('.no_pages').html_safe

  %p.adminButtons
    - if authorizer.can_add_page?(nil)
      = link_to t('.create_root_page'), new_page_path(version_ordinal: @version.ordinal), :class => 'button new'
    - if authorizer.can_reposition_page?(nil) && @version.pages.roots.localized(I18n.locale).present?
      = link_to t('.reorder_root_pages'), page_positioning_path, :class => 'button'

app/views/documentation/pages/positioning.html.haml
- canDelete = authorizer.can_delete_page?(@page)

- if @page
  - @page_title = @page.breadcrumb.reverse.map(&:title).join(" - ")
  = documentation_breadcrumb_for @version, @page
- else
  - @page_title = t('.reorder_root_pages_title')
  = documentation_breadcrumb_for @version, nil

%section.page
  %h1= @page ? @page.title : t('.reorder_root_pages_title')

  = form_tag page_positioning_path(@page.try(:full_permalink), version_ordinal: @version.ordinal), :class => 'reordering' do
    %ul
      - for child in @pages
        %li
          = child.title
          = hidden_field_tag 'order[]', child.id
          - if canDelete
            .inlineActions
              = link_to t('.delete'), delete_page_path(child.full_permalink, version_ordinal: @version.ordinal, redirect_to: :back),
                :class => 'button delete', :method => :delete, :data => {:confirm => t('.confirm_delete')}
            .clearfix


  %p.adminButtons
    - if @page
      = link_to t('.back_to_page'), page_path(@page.full_permalink, version_ordinal: @version.ordinal), :class => 'button edit'
    - else
      = link_to t('.back_to_homepage'), root_path, :class => 'button edit'

app/views/documentation/pages/screenshot.html.haml
= form_for @screenshot, :url => upload_screenshot_path, :html => {:class => 'pageForm'} do |f|
  %dl
    %dt= f.label :upload_file
    %dd.padded
      - if params[:filename]
        = params[:filename]
      - else
        = f.file_field :upload_file

  %dl
    %dt= f.label :alt_text
    %dd= f.text_field :alt_text

  %p.submit
    = f.submit "Upload Screenshot", :class => 'button'

app/views/documentation/pages/search.html.haml
- @page_title = t('.title', :query => params[:query])

%section.page
  
  - if @result.empty?
    %p.noSearchResults= t('.no_results', :query => params[:query])
  - else
    %h1= t('.title', :query => params[:query])
    %p.searchSummary= documentation_search_summary(@result)
    = documentation_search_results(@version, @result)
    %p.pagination= documentation_search_pagination(@version, @result, :link_class => 'button')
    

app/views/documentation/pages/show.html.haml
- @page_title = @page.breadcrumb.reverse.map(&:title).join(" - ")

= documentation_breadcrumb_for @version, @page

%section.page
  - if @page.preview_path
    %p.previewLink= link_to t('.view_in_website'), @page.preview_path, :class => 'button preview'

  %h1= @page.title
  %p.updated= t('.last_updated', :timestamp => @page.updated_at.to_s(:long))
  .documentationMarkdown
    ~ preserve(documentation_content_for(@version, @page))

  = render 'admin_buttons'